services:
  # Backend Service
  - type: web
    name: healthbridge-backend
    env: java
    plan: starter
    buildCommand: cd backend && mvn clean install
    startCommand: cd backend && java -jar target/healthbridge-backend-1.0.0.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: healthbridge-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: MAIL_USERNAME
        value: healthbridge13012002@gmail.com
      - key: MAIL_PASSWORD
        value: bisvrfctijbvfnbu
      - key: GOOGLE_CLIENT_ID
        value: your-google-client-id
      - key: GOOGLE_CLIENT_SECRET
        value: your-google-client-secret
      - key: RAZORPAY_KEY_ID
        value: your-razorpay-key-id
      - key: RAZORPAY_SECRET
        value: your-razorpay-secret

  # Frontend Service
  - type: web
    name: healthbridge-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: API_URL
        fromService:
          type: web
          name: healthbridge-backend
          property: host

  # Database
  - type: pserv
    name: healthbridge-db
    env: mysql
    plan: starter
    region: oregon
