services:
  # Backend Service
  - type: web
    name: healthbridge-backend
    env: java
    plan: starter
    rootDir: backend
    buildCommand: mvn clean install -DskipTests
    startCommand: java -Dserver.port=$PORT -Dspring.profiles.active=prod -jar target/healthbridge-backend-1.0.0.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        value: "8081"
      - key: DATABASE_URL
        value: "jdbc:mysql://tramway.proxy.rlwy.net:23911/railway?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
      - key: DB_USERNAME
        value: "root"  
      - key: DB_PASSWORD
        value: "wHZXIDkxfIhahvxrWjAPIKJLRTeUboOc"
      - key: JWT_SECRET
        generateValue: true
      - key: MAIL_USERNAME
        value: healthbridge13012002@gmail.com
      - key: MAIL_PASSWORD
        value: bisvrfctijbvfnbu
      - key: GOOGLE_CLIENT_ID
        value: your-google-client-id
      - key: GOOGLE_CLIENT_SECRET
        value: your-google-client-secret
      - key: RAZORPAY_KEY_ID
        value: your-razorpay-key-id
      - key: RAZORPAY_SECRET
        value: your-razorpay-secret
      - key: CORS_ORIGINS
        value: "https://healthbridge-frontend.onrender.com,http://localhost:4200"

  # Frontend Service
  - type: web
    name: healthbridge-frontend
    env: node
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm run serve
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
      - path: /_redirects
        name: Content-Type
        value: text/plain
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: API_URL
        fromService:
          type: web
          name: healthbridge-backend
          property: host
