server:
  port: ${PORT:8081}

spring:
  application:
    name: healthbridge-backend
  banner:
    mode: console
  
  datasource:
    url: jdbc:mysql://tramway.proxy.rlwy.net:23911/railway?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: wHZXIDkxfIhahvxrWjAPIKJLRTeUboOc
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      jdbc-url: jdbc:mysql://tramway.proxy.rlwy.net:23911/railway?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      username: root
      password: wHZXIDkxfIhahvxrWjAPIKJLRTeUboOc
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  sql:
    init:
      mode: always
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        connection:
          url: jdbc:mysql://tramway.proxy.rlwy.net:23911/railway?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
          username: root
          password: wHZXIDkxfIhahvxrWjAPIKJLRTeUboOc
          driver_class: com.mysql.cj.jdbc.Driver
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:healthbridge13012002@gmail.com}
    password: ${MAIL_PASSWORD:bisvrfctijbvfnbu}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
  
  # OAuth2 Configuration
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:your-google-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:your-google-client-secret}
            scope: profile,email

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:healthbridge-secret-key-2023-very-long-secret-key-for-jwt-token-generation}
  expiration: 86400000 # 24 hours in milliseconds

# File Upload Configuration
file:
  upload:
    directory: uploads/
    max-size: 10485760 # 10MB

# CORS Configuration
cors:
  allowed-origins: ${CORS_ORIGINS:http://localhost:4200,https://healthbridge-frontend.onrender.com}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

# Razorpay Configuration
razorpay:
  key:
    id: ${RAZORPAY_KEY_ID:your-razorpay-key-id}
    secret: ${RAZORPAY_SECRET:your-razorpay-secret}

# Logging Configuration
logging:
  level:
    com.healthbridge: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.orm.jpa: DEBUG
    org.springframework.boot.autoconfigure: DEBUG
    org.springframework.boot.autoconfigure.jdbc: DEBUG
    org.springframework.boot.autoconfigure.orm.jpa: DEBUG
    org.hibernate.engine.jdbc: DEBUG
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/healthbridge.log
