server:
  port: 8081

spring:
  application:
    name: healthbridge-backend
  
  datasource:
    url: jdbc:mysql://localhost:3306/healthprj?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Sonu@12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  
  devtools:
    restart:
      enabled: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: healthbridge13012002@gmail.com
    password: bisvrfctijbvfnbu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
  

# JWT Configuration
jwt:
  secret: healthbridge-secret-key-2023-very-long-secret-key-for-jwt-token-generation
  expiration: 86400000 # 24 hours in milliseconds

# File Upload Configuration
file:
  upload:
    directory: uploads/
    max-size: 10485760 # 10MB

# CORS Configuration
cors:
  allowed-origins: http://localhost:4200,http://localhost:4201,http://127.0.0.1:4200,http://127.0.0.1:4201,http://10.45.254.162:4200
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

# Frontend URL Configuration
frontend:
  url: http://localhost:4200


# Razorpay Configuration
razorpay:
  key:
    id: ${RAZORPAY_KEY_ID:your-razorpay-key-id}
    secret: ${RAZORPAY_SECRET:your-razorpay-secret}

# Logging Configuration
logging:
  level:
    com.healthbridge: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    root: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/healthbridge.log
