server:
  port: ${PORT:8081}

spring:
  application:
    name: healthbridge-backend
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/healthbridge?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: always

jwt:
  secret: ${JWT_SECRET:healthbridge-secret-key-2023-very-long-secret-key-for-jwt-token-generation}
  expiration: 86400000

cors:
  allowed-origins: ${CORS_ORIGINS:http://localhost:4200,https://healthbridge-frontend-jj1l.onrender.com}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

# Razorpay Configuration
razorpay:
  key:
    id: ${RAZORPAY_KEY_ID:rzp_test_1234567890}
    secret: ${RAZORPAY_SECRET:your-razorpay-secret}

logging:
  level:
    com.healthbridge: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    root: INFO