server:
  port: ${PORT:8081}

spring:
  application:
    name: healthbridge-backend
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/healthbridge?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:healthbridge13012002@gmail.com}
    password: ${MAIL_PASSWORD:bisvrfctijbvfnbu}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:468629260262-6ua09pru34mlsjerlvuhjocvn09mrlje.apps.googleusercontent.com}
            client-secret: ${GOOGLE_CLIENT_SECRET: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}
            scope: profile,email
            redirect-uri: https://healthbridge-1-piny.onrender.com/login/oauth2/code/google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v2/userinfo
            user-name-attribute: email

jwt:
  secret: ${JWT_SECRET:healthbridge-secret-key-2023-very-long-secret-key-for-jwt-token-generation}
  expiration: 86400000

cors:
  allowed-origins: ${CORS_ORIGINS:http://localhost:4200,https://healthbridge-frontend-jj1l.onrender.com}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

frontend:
  url: ${FRONTEND_URL:https://healthbridge-frontend-jj1l.onrender.com}

razorpay:
  key:
    id: ${RAZORPAY_KEY_ID:rzp_test_ePOPRenR20mzsg}
    secret: ${RAZORPAY_SECRET:WLGtxuC251XBSyZiEwyIR3gA}

logging:
  level:
    com.healthbridge: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    root: INFO